# safelist
branches:
  only:
  - master
  - stable

dist: xenial
sudo: required
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "python3-setuptools"
      - "python3-dev"
      - "libtiff4-dev"
      - "libjpeg8-dev"
      - "zlib1g-dev"
      - "libfreetype6-dev"
      - "liblcms2-dev"
      - "libwebp-dev"
      - "tcl8.5-dev"
      - "tk8.5-dev"
script:
  - python3 --version
  - sudo pip install awscli
  - sudo pip3 install -r requirements.txt
  - wget https://github.com/gohugoio/hugo/releases/download/v0.46/hugo_0.46_Linux-64bit.deb
  - sudo dpkg -i hugo_0.46_Linux-64bit.deb
  - sudo python3 ./map.py || echo 'Failed'
  - HUGO_ENV="production" hugo -F
  - aws s3 sync --delete public/ s3://holidays-aldanet-fr/ --acl public-read
  - mkdir ~/.aws
  - echo "[preview]" > ~/.aws/config
  - echo "cloudfront = true" >> ~/.aws/config
  - aws cloudfront create-invalidation --distribution-id ECZZSHTS6GEXC --paths "/*"
notifications:
    email:
        on_failure: always
